### ISSUE TITLE
Troppo pochi insulti

### ISSUE THREAD

**Issue by federico1564S** [RichyZ99/Insultator#1]
Occorre ampliare il tutto quest’estate (e non so fare una richiesta di tiraggio), purtroppo non sono disponibili prima della terza prova

**Comment by RichyZ99** [comment]
Siccome anch’io ho intenzione di portare a 1000 il numero finale degli insulti, oltre che dividerli in 10 categorie anziché in otto, chiudo questo problema con la promessa che tutto sarà risolto.
